CREATE TABLE "order" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_warehouse" bigint,
  "id_shipping" bigint,
  "order_code" varchar(50),
  "order_type" varchar(30),
  "status" varchar(30),
  "created_at" timestamp
);

CREATE TABLE "product" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_code" varchar(50),
  "name" varchar(255),
  "uom" varchar(30),
  "created_at" timestamp
);

CREATE TABLE "document" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint,
  "document_no" varchar(50),
  "type" varchar(30) NOT NULL,
  "status" varchar(30),
  "created_at" timestamp
);

CREATE TABLE "order_product" (
  "id" bigint,
  "id_order" bigint NOT NULL,
  "product_code" int,
  "created_at" timestamp,
  PRIMARY KEY ("id_order")
);

CREATE TABLE "task_template" (
  "id" number PRIMARY KEY,
  "type" number
);

CREATE TABLE "task_template_condition" (
  "id" number PRIMARY KEY,
  "task_template_id" number,
  "task_code" varchar2
);

CREATE TABLE "position_temp" (
  "id_task_template_task" number,
  "id_position" number
);

CREATE TABLE "position" (
  "id" number PRIMARY KEY
);

CREATE TABLE "position_warehouse" (
  "id_plant_wh" number,
  "id_position" number,
  "id_employee" number
);

CREATE TABLE "task" (
  "id" number PRIMARY KEY,
  "id_order" number
);

CREATE TABLE "bbbg" (
  "id" number PRIMARY KEY,
  "task_id" number
);

CREATE TABLE "bbbg_signature" (
  "id" number PRIMARY KEY,
  "bbbg_id" number
);

CREATE TABLE "employee" (
  "id" number PRIMARY KEY
);

CREATE TABLE "task_KPI" (
  "id" number PRIMARY KEY,
  "id_task" number
);

CREATE TABLE "info_shipping" (
  "id" number PRIMARY KEY
);

CREATE TABLE "info_shipping_issue" (
  "id" number PRIMARY KEY,
  "shipping_id" number
);

CREATE TABLE "upload" (
  "id_task" number
);

CREATE TABLE "history_action_log" (
  "id_task" number,
  "id_order" number,
  "type" number
);

CREATE TABLE "plant_wh" (
  "id" number PRIMARY KEY
);

CREATE TABLE "scan_product_log" (
  "id" number PRIMARY KEY
);

CREATE TABLE "plant_wh_pro" (
  "id_order_pro" number,
  "id_wh_plant" number
);

CREATE TABLE "order_pro_component" (
  "id" bigint PRIMARY KEY,
  "id_product" int,
  "order_pro_id" bigint NOT NULL,
  "unit_qty" decimal(18,2),
  "expected_qty" decimal(18,2),
  "created_at" timestamp
);

CREATE TABLE "product_inventory" (
  "id" number PRIMARY KEY,
  "product_id" number,
  "plant_wh_id" number,
  "quantity_on_hand" number,
  "quantity_reserved" number,
  "quantity_available" number
);

CREATE TABLE "organization" (
  "id" number PRIMARY KEY
);

CREATE TABLE "handling_unit" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hu_code" varchar(100) UNIQUE NOT NULL,
  "zone_equipment_id" bigint
);

CREATE TABLE "handling_unit_item" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hu_id" bigint NOT NULL,
  "order_product_component_id" bigint,
  "warehouse_zone_equipment_id" number
);

CREATE TABLE "warehouse_zone_equipment" (
  "id" number PRIMARY KEY
);

COMMENT ON TABLE "handling_unit" IS '1 HU vật lý. KHÔNG FK order — vào lệnh qua component → order_product → order. SL chi tiết nằm ở item.';

COMMENT ON TABLE "handling_unit_item" IS '1 dòng UI = 1 item. Trỏ component (cha hoặc con) — KHÔNG trỏ order_product.';

ALTER TABLE "order_product" ADD FOREIGN KEY ("id_order") REFERENCES "order" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "handling_unit" ADD FOREIGN KEY ("zone_equipment_id") REFERENCES "warehouse_zone_equipment" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "handling_unit_item" ADD FOREIGN KEY ("hu_id") REFERENCES "handling_unit" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "task" ADD FOREIGN KEY ("id_order") REFERENCES "order" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "info_shipping_issue" ADD FOREIGN KEY ("shipping_id") REFERENCES "info_shipping" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bbbg" ADD FOREIGN KEY ("task_id") REFERENCES "task" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "document" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "task_KPI" ADD FOREIGN KEY ("id_task") REFERENCES "task" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "info_shipping" ADD FOREIGN KEY ("id") REFERENCES "order" ("id_shipping") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "upload" ADD FOREIGN KEY ("id_task") REFERENCES "task" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "history_action_log" ADD FOREIGN KEY ("id_task") REFERENCES "task" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "position_temp" ADD FOREIGN KEY ("id_position") REFERENCES "position" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "position_warehouse" ADD FOREIGN KEY ("id_position") REFERENCES "position" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "position_warehouse" ADD FOREIGN KEY ("id_employee") REFERENCES "employee" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "position_temp" ADD FOREIGN KEY ("id_task_template_task") REFERENCES "task_template" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plant_wh_pro" ADD FOREIGN KEY ("id_wh_plant") REFERENCES "plant_wh" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "plant_wh_pro" ADD FOREIGN KEY ("id_order_pro") REFERENCES "order_pro_component" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "position_warehouse" ADD FOREIGN KEY ("id_plant_wh") REFERENCES "plant_wh" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "task_template_condition" ADD FOREIGN KEY ("task_template_id") REFERENCES "task_template" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_pro_component" ADD FOREIGN KEY ("order_pro_id") REFERENCES "order_product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bbbg_signature" ADD FOREIGN KEY ("id") REFERENCES "bbbg" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "handling_unit_item" ADD FOREIGN KEY ("order_product_component_id") REFERENCES "order_pro_component" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_pro_component" ADD FOREIGN KEY ("id_product") REFERENCES "order_pro_component" ("id") DEFERRABLE INITIALLY IMMEDIATE;
